### ISSUE TITLE
Audit Script 2 errors 

### ISSUE THREAD

**Issue by rmmcmahon** [jamf/CIS-for-macOS-Catalina-CP#4]
For 2.6.4 in audit script - the audit for 2.6.4 is incorrect when calling out the audit and plistlocation - its a typo - 2_7_4 
	Audit2_7_4="$(defaults read "$plistlocation" OrgScore2_7_4)"

For 2.5.1.2 in audit script - the audit for 2.5.1.2 is incorrect when calling out the plistlocation - its a typo - 2_6_1_2 
	Audit2_5_1_2="$(defaults read "$plistlocation" OrgScore2_6_1_2)"

**Comment by erinmc** [comment]
Resolved
