### ISSUE TITLE
ENHANCEMENT REQUEST: Use absolute path for `systemsetup` binary

### ISSUE THREAD

**Issue by yoopersteeze** [jamf/CIS-for-macOS-Catalina-CP#5]
In the remediation script, if 2.4.1(Remote Apple Events) is enabled, the remediation fails since the absolute path is not used.

`Script result: setremoteappleevents: Turning Remote AppleEvents on or off requires Full Disk Access privileges.`

Updating the script to use `/usr/sbin/systemsetup -setremoteappleevents off` resolves that issue. 

Jamf PPPC profile is installed.

**Comment by erinmc** [comment]
Added full path
